# Generated by Django 4.2.3 on 2024-05-13 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_funds'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Funds',
            new_name='Fund',
        ),
    ]
