# Generated by Django 4.2.3 on 2024-06-06 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profitloss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=500000.0, max_digits=10),
        ),
    ]
