# Generated by Django 4.2.3 on 2023-12-05 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_portfolio_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfoliostock',
            old_name='avg_price',
            new_name='purchase_price',
        ),
    ]
