# Generated by Django 4.2.3 on 2023-12-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_rename_avg_price_portfoliostock_purchase_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfoliostock',
            old_name='purchase_price',
            new_name='avg_price',
        ),
        migrations.AlterField(
            model_name='portfoliostock',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
