# Generated by Django 4.2.3 on 2023-12-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_rename_purchase_price_portfoliostock_avg_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfoliostock',
            old_name='quantity',
            new_name='total_quantity',
        ),
        migrations.RemoveField(
            model_name='portfoliostock',
            name='avg_price',
        ),
        migrations.AddField(
            model_name='portfoliostock',
            name='avg_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='portfoliostock',
            name='total_investment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
