# Generated by Django 4.2.3 on 2023-12-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_rename_quantity_portfoliostock_total_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='portfolio_worth',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
