# Generated by Django 4.2.3 on 2024-06-26 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0010_alter_portfolio_stocks_alter_position_stock"),
    ]

    operations = [
        migrations.RenameField(
            model_name="portfolio",
            old_name="stocks",
            new_name="securities",
        ),
        migrations.RenameField(
            model_name="position",
            old_name="stock",
            new_name="security",
        ),
    ]
