# Generated by Django 4.2.3 on 2023-11-19 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockname',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
