# Generated by Django 4.2.3 on 2023-11-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_stockname_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdata',
            name='ltp',
            field=models.FloatField(default='0.00'),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='close',
            field=models.FloatField(default='0.00'),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='high',
            field=models.FloatField(default='0.00'),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='low',
            field=models.FloatField(default='0.00'),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='open',
            field=models.FloatField(default='0.00'),
        ),
    ]
