# Generated by Django 4.2.3 on 2023-12-26 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_alter_stockdata_close_alter_stockdata_high_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockname',
            options={'ordering': ['name']},
        ),
    ]
