# Generated by Django 4.2.3 on 2024-06-24 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0005_alter_stockname_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Security",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=100, unique=True)),
                ("securityName", models.CharField(max_length=100)),
            ],
            options={
                "ordering": ["securityName"],
            },
        ),
        migrations.CreateModel(
            name="SecurityData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lastTradedPrice",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "openPrice",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "highPrice",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "lowPrice",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "previousClose",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
            ],
            options={
                "ordering": ["security"],
            },
        ),
        migrations.DeleteModel(
            name="StockData",
        ),
    ]
