# Generated by Django 4.2.3 on 2024-06-26 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0007_delete_stockname_securitydata_security"),
    ]

    operations = [
        migrations.AddField(
            model_name="securitydata",
            name="lastUpdatedDate",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
