# Generated by Django 4.2.3 on 2024-06-26 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0008_securitydata_lastupdateddate"),
    ]

    operations = [
        migrations.RenameField(
            model_name="securitydata",
            old_name="lastUpdatedDate",
            new_name="lastUpdatedDateTime",
        ),
    ]
